name: WebApp
summary: Azure Web App Environment
description: Deploys an Azure Web App without a data store
runner: ARM
templatePath: main.json

parameters:
  - id: name
    name: Name
    description: 'Name of the Web App.'
    type: string
    required: true