name: tour-of-heroes-dotnet
summary: Azure Web App Environment
description: Deploys an Azure Web App without a data store
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: name
    name: name
    description: 'Name of the Web App.'
    type: string
    required: true